# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2
project_name: remarkabledayone
report_sizes: true
metadata:
  mod_timestamp: "{{ .CommitTimestamp }}"
builds:
  - main: ./cmd/remarkabledayone
    flags:
      - -trimpath
    ldflags:
      - -s
      - -w
      ## <<Stencil::Block(remarkabledayoneLdflags)>>

      ## <</Stencil::Block>>
    env:
      - CGO_ENABLED=0
    goarch:
      - amd64
      - arm64
      ## <<Stencil::Block(remarkabledayoneExtraArch)>>

      ## <</Stencil::Block>>
    goos:
      - linux
      - darwin
      - windows
      ## <<Stencil::Block(remarkabledayoneExtraOS)>>

      ## <</Stencil::Block>>
    ignore:
      - goos: windows
        goarch: arm
    mod_timestamp: "{{ .CommitTimestamp }}"
checksum:
  name_template: "checksums.txt"
snapshot:
  version_template: "{{ incpatch .Version }}-next"
changelog:
  use: git
release:
  prerelease: "auto"
  footer: |-
    **Full Changelog**: https://github.com/jaredallard/remarkabledayone/compare/{{ .PreviousTag }}...{{ .Tag }}

## <<Stencil::Block(extraReleaseOpts)>>
brews:
  - commit_author:
      name: GitHub Actions
      email: 41898282+github-actions[bot]@users.noreply.github.com
    homepage: https://github.com/jaredallard/remarkabledayone
    license: AGPL-3.0
    caveats: |
      Dayone must be installed manually from the app store.
      Inkscape must be installed manually via `brew install --cask inkscape`.
      rmc must be installed manually. Recommend path is to use `uv` to
      install it:

        brew install uv
        uv tool install rmc
    description: "A utility to sync pages from a Remarkable 2 tablet to Day One"
    dependencies:
      - name: imagemagick
        os: mac
    repository:
      owner: jaredallard
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
## <</Stencil::Block>>
