# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj
project_name: remarkabledayone
before:
  hooks:
    - go mod tidy
builds:
  - main: ./cmd/{{ .ProjectName }}
    flags:
      - -trimpath
    ldflags:
      - -s
      - -w
    env:
      - CGO_ENABLED=0
    goarch:
      - amd64
      - arm64
    goos:
      - linux
      - darwin
archives:
  - format: tar.xz
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-next"
brews:
  - commit_author:
      name: GitHub Actions
      email: 41898282+github-actions[bot]@users.noreply.github.com
    homepage: https://github.com/jaredallard/remarkabledayone
    license: AGPL-3.0
    description: "A utility to sync pages from a Remarkable 2 tablet to Day One"
    dependencies:
      - name: imagemagick
        os: mac
      - name: inkscape
        os: mac
    repository:
      owner: jaredallard
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN}}"
changelog:
  sort: asc
  use: git
  filters:
    exclude:
      - "^test:"
      - "^chore:"
      - "merge conflict"
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
      - go mod tidy
  groups:
    - title: Dependency updates
      regexp: "^.*(feat|chore|fix)\\(deps\\)*:+.*$"
      order: 300
    - title: "New Features"
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 100
    - title: "Bug fixes"
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 200
    - title: "Documentation updates"
      regexp: "^.*docs[(\\w)]*:+.*$"
      order: 400
    - title: Other work
      order: 9999

release:
  footer: |-
    **Full Changelog**: https://github.com/jaredallard/remarkabledayone/compare/{{ .PreviousTag }}...{{ .Tag }}
